version: '3.8'

services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    mem_limit: 512m
    cpus: 0.2
    networks:
      - default

volumes:
  rabbitmq_data:
    driver: local

networks:
  default:
    driver: bridge
